version: "3.8"
name: comtrans
services:

  db:
    image: postgres:13-alpine
    container_name: user_db_server
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    ports:
      # - 6543:5432
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    restart: unless-stopped

  app:
    build: ./backend
    container_name: ctback
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy

  userservice:
   image: userservice:latest
   container_name: userservice
   environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: postgres
   ports:
    - "8080:80"
   depends_on:
    - db

  ctwebui:
    build: ./client/ctwebclient
    container_name: ctwebui
    ports:
      - 5000:80

volumes:
  db-data:

networks:
  default:
    external:
      name: nat
